package com.info.demo.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.Date;
/*
@Data annotation is used for getter and setter
*/

/*
@Data annotation is the feature from Lombok and used for getter and setter
@Entity annotation define the class as an entity class
@Table annotation along with name argument is used to define the table name
*/

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "sales_man_message_to_customer")
// Create SalesManMessageToCustomer class to store Sales Man's Autogenerated Message which is sent To Customer in the workflow
public class SalesManMessageToCustomer {
    /*
        @Id annotation will behave as the primary key attribute in the table
        @Generatedvalue(strategy = generationtype.auto) in order to auto increment the primary key attribute
    */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne(targetEntity = Customer.class, fetch = FetchType.EAGER)
    @JoinColumn(name = "customer_id")
    private Customer customer;

    @ManyToOne(targetEntity = StageWiseMessage.class, fetch = FetchType.EAGER)
    @JoinColumn(name = "message_id")
    private StageWiseMessage message;

    @Column(name = "stage", nullable = false)
    private int stage;

    @Column(name = "create_date", nullable = false)
    private Date createDate;
}
